export const STRINGS = {
    sectionTitle: 'Meal planner',
    library: 'Library',
    categories: 'Categories',
    addFood: '+ Food',
    addRecipe: '+ Recipe',
    import: 'Import',
    export: 'Export',
    today: 'Today',
    day: 'Day',
    week: 'Week',
    month: 'Month',
    shoppingList: 'Shopping list',
    mealTemplate: 'Meal template',
    print: 'Print',
    nutrition: 'Nutrition',
    search: 'Search foods & recipes…',
    noItems: 'No items yet',
    emptyLibrary: 'Your library is empty. Start by adding a food or a recipe.',
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
    name: 'Name',
    servings: 'Servings',
    servingG: 'Default serving (g)',
    kcal: 'kcal',
    protein: 'Protein',
    carbs: 'Carbs',
    fat: 'Fat',
    fiber: 'Fiber',
    sugar: 'Sugar',
    sodium: 'Sodium',
    nutritionPer100g: 'Nutrition per 100 g',
    ingredients: 'Ingredients',
    instructions: 'Instructions',
    description: 'Description',
    addIngredient: '+ Add ingredient',
    category: 'Category',
    dropHere: 'Drop here',
    grams: 'grams',
    amountG: 'Amount (g)',
    required: 'Required',
    invalidNumber: 'Must be a number ≥ 0',
    exportFilename: (iso) => `corevital-health-${iso}.json`,
    importReplace: 'Replace all',
    importMergeImported: 'Merge (prefer imported)',
    importMergeLocal: 'Merge (prefer local)',
    importSuccess: (n) => `Imported ${n} items`,
    exportSuccess: 'Exported JSON',
    moveTo: 'Move to…',
    removeEntry: 'Remove',
    clearDay: 'Clear day',
    confirmClearDay: (label) => `Clear all planned items for ${label}?`,
    confirmDelete: (name) => `Delete "${name}"?`,
    missing: '(missing)',
    perServing: 'Per serving',
    total: 'Total',
    weekStartsOn: 'Week starts on',
    calorieTarget: 'Daily calorie target',
    macroTargets: 'Macro targets (g)',
    settings: 'Settings',
    breakfast: 'Breakfast',
    lunch: 'Lunch',
    dinner: 'Dinner',
    snack: 'Snack',
    dessert: 'Dessert',
    drink: 'Drink',
};
